version: "3.1"
services:
    mysql-concurrency-test:
        image: neznajki/mysql-concurrency-test
        container_name: mysql-concurrency-test
        environment:
          - dbhost=mysql-concurrency-test-db
          - dbport=3306
          - dbname=test_concurency
          - dbuser=root
          - dbpassword=p1assword
          - concurrecncy=100
          - executions=5000
          - engine=MyISAM
        depends_on:
          - mysql-concurrency-test-db

    mysql-concurrency-test-db:
        hostname: mysql-concurrency-test-db
        image: mysql:5.7
        container_name: mysql-concurrency-test-db
        environment:
            MYSQL_DATABASE: 'authorization'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: '1'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'p1assword'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted

networks:
    default:
        external:
            name: local.net